"""
models_db.py
------------
SQLAlchemy ORM table definitions for the ML service's own tables.

The ML service only owns `TrainingSample`.
`Batch` records are created by Next.js via Prisma — the ML service
never writes to the Batch table directly.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, String
from sqlalchemy.orm import Mapped, mapped_column

from db import Base


class TrainingSample(Base):
    """
    Stores one row per /predict call so Phase 5 fine-tuning has real data.

    Fields mirror the Prisma schema in architecture.md §5 exactly:
        id, imageUrl, predictedLabel, correctedLabel, usedInRetrain
    """

    __tablename__ = "training_samples"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        comment="CUID/UUID generated by the application layer.",
    )
    imageUrl: Mapped[str] = mapped_column(
        String(2048),
        nullable=False,
        comment="Public URL or upload identifier for the scanned image.",
    )
    predictedLabel: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        comment="Raw label string returned by the HF model.",
    )
    correctedLabel: Mapped[str | None] = mapped_column(
        String(128),
        nullable=True,
        default=None,
        comment="User-supplied correction (Phase 5); NULL until corrected.",
    )
    usedInRetrain: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment="Set to True after this sample has been included in a retrain job.",
    )
    createdAt: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    def __repr__(self) -> str:
        return (
            f"<TrainingSample id={self.id!r} "
            f"label={self.predictedLabel!r} "
            f"corrected={self.correctedLabel!r}>"
        )
